// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADb_359Z3MxgB1cvXigJD26cjDSfB-v1g',
    appId: '1:877332308693:web:50d5bae44e40cd1595785c',
    messagingSenderId: '877332308693',
    projectId: 'sitjsochurch',
    authDomain: 'sitjsochurch.firebaseapp.com',
    storageBucket: 'sitjsochurch.firebasestorage.app',
    databaseURL: 'https://sitjsochurch-default-rtdb.firebaseio.com',
    measurementId: 'G-RZ8LQFBK7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjDfMk7P7ysavGWCwJ8ymb90JUojEivJw',
    appId: '1:877332308693:android:b907ce12657da5cd95785c',
    messagingSenderId: '877332308693',
    projectId: 'sitjsochurch',
    databaseURL: 'https://sitjsochurch-default-rtdb.firebaseio.com',
    storageBucket: 'sitjsochurch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdQ4vS_dOwLSscO-D7o_T1d8cWGOAtwMQ',
    appId: '1:877332308693:ios:b6f1e5bea9a3bf4595785c',
    messagingSenderId: '877332308693',
    projectId: 'sitjsochurch',
    databaseURL: 'https://sitjsochurch-default-rtdb.firebaseio.com',
    storageBucket: 'sitjsochurch.firebasestorage.app',
    iosBundleId: 'com.sit.jsochurch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdQ4vS_dOwLSscO-D7o_T1d8cWGOAtwMQ',
    appId: '1:877332308693:ios:e1a0546469426d2295785c',
    messagingSenderId: '877332308693',
    projectId: 'sitjsochurch',
    databaseURL: 'https://sitjsochurch-default-rtdb.firebaseio.com',
    storageBucket: 'sitjsochurch.firebasestorage.app',
    iosBundleId: 'com.gbs.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADb_359Z3MxgB1cvXigJD26cjDSfB-v1g',
    appId: '1:877332308693:web:aed48581ac63236495785c',
    messagingSenderId: '877332308693',
    projectId: 'sitjsochurch',
    databaseURL: 'https://sitjsochurch-default-rtdb.firebaseio.com',
    authDomain: 'sitjsochurch.firebaseapp.com',
    storageBucket: 'sitjsochurch.firebasestorage.app',
    measurementId: 'G-4WRF7R2R64',
  );
}
